name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 requests pyinstaller
      
      - name: Build with PyInstaller
        run: |
          pyinstaller --name=wallppy \
                      --windowed \
                      --onefile \
                      main.py
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/wallppy
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}